version: '3'
services:
  client: 
    # image?
    image: node:16
    container_name: demo_docker_client
    # are ports needed?
    ports:
      - 8080:8080
    # where is the code and should we access it?
    volumes:
      - type: bind
        source: ./client
        target: /code
    working_dir: /code
    # what to do once the container has started?
    command: bash -c "npm install && npm run dev"
    depends_on:
      - server
  server: 
    # pick an image?
    image: node:18
    container_name: just_api
    # do we need to expose ports?
    ports: 
      - 3000:3000
    # where does the code live?
    volumes: 
      - type: bind
        source: ./server
        target: /code
    working_dir: /code
    # what to do once the container is up and running
    command: bash -c "npm install && npm run dev"